<?php
/**
 * Created by bianquan
 * User: ZhuYunlong
 * Email: 920200256@qq.com
 * Date: 2019/1/23
 * Time: 22:04
 */

namespace app\common\controller;


use app\adminApi\model\Api;
use app\adminApi\service\Auth;
use app\adminApi\service\Token;
use app\lib\exception\AuthException;
use app\lib\exception\UnknownException;
use app\lib\Response;
use think\Cache;
use think\Controller;
use think\Request;

class BaseController extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $request = Request::instance();
        //所有ajax请求的options预请求都会直接返回200，如果需要单独针对某个类中的方法，可以在路由规则中进行配置
        if($request->isOptions()){
            return json(['msg'=>'success'],200);
        }
//        Cache::clear();
        $module = $request->module();
        $controller = $request->controller();
        $action = $request->action();
        if(empty($module)) $module = 'index';
        if(empty($controller)) $controller = 'Index';
        if(empty($action)) $action = 'index';
        $api = strtolower($module.'/'.$controller.'/'.$action);

        Auth::init($api);
    }




}