<?php
/**
 * Created by bianquan
 * User: ZhuYunlong
 * Email: 920200256@qq.com
 * Date: 2019/1/23
 * Time: 22:04
 */

namespace app\common\controller;


use app\admin\model\Api;
use app\admin\service\Auth;
use app\admin\service\Token;
use app\lib\exception\AuthException;
use app\lib\exception\UnknownException;
use app\lib\Response;
use think\Cache;
use think\Controller;
use think\Request;

class BaseController extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }




}