<?php
/**
 * Created by bianquan
 * User: ZhuYunlong
 * Email: 920200256@qq.com
 * Date: 2019/1/12
 * Time: 20:07
 */

namespace app\adminApi\controller;


use app\adminApi\service\Token;
use app\lib\exception\TokenException;
use think\Controller;
use think\Request;

class BaseController extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $request = Request::instance();
        //所有ajax请求的options预请求都会直接返回200，如果需要单独针对某个类中的方法，可以在路由规则中进行配置
        if($request->isOptions()){
            return json(['msg'=>'success'],200);
        }
        $path = $request->path();
        if(!in_array($path, config('auth.allowedNoToken'))) {
            $token = $request->header('X-Api-Token');
            $adminID = Token::checkToken($token);
            $auth = Token::checkAuth($adminID,$path);
            if(!$auth) {
                throw new TokenException(['msg'=>'访问越权，请查看用户权限']);
            }
        }
    }

}